apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - netbirdproxy-configmap.yaml
  - netbirdproxy-deployment.yaml
  - netbirdproxy-networkpolicy.yaml
  - netbirdproxy-persistentvolume.yaml
  - netbirdproxy-service.yaml
  - superlink-deployment.yaml
  - superlink-persistentvolume.yaml
  - superlink-service.yaml

configMapGenerator:
- name: netbirdproxy-params
  literals:
    - management-url=THIS_WILL_BE_REPLACED_BY_ARGOCD
    - management-host=THIS_WILL_BE_REPLACED_BY_ARGOCD

# Patch netbirdproxy-networkpolicy to allow egress to management-host
replacements:
  - source:
      kind: ConfigMap
      name: netbirdproxy-params
      fieldPath: data.management-host
    targets:
      - select:
          kind: CiliumNetworkPolicy
          name: netbirdproxy
        fieldPaths:
          - spec.egress.1.toFQDNs.0.matchName

patches:
  # Set storageClassName in kustomize so we can deploy manifests outside K8TRE
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: rwo-default
