---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbirdproxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: netbirdproxy
  template:
    metadata:
      labels:
        app: netbirdproxy
    spec:
      containers:
        - name: proxy
          # image: docker.io/library/haproxy:3.3.7-alpine
          image: docker.io/library/haproxy:3.3.7
          ports:
            - containerPort: 9091
            - containerPort: 9092
            - containerPort: 9093
            - name: stats
              containerPort: 8404
          volumeMounts:
            - name: proxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg

        # - name: dnsmasq
        #   image: docker.io/4km3/dnsmasq:2.90-r3
        #   ports:
        #     - containerPort: 53

        # https://docs.netbird.io/use-cases/cloud/routing-peers-and-kubernetes#step-4-deploy-the-net-bird-agent
        - name: netbird
          image: docker.io/netbirdio/netbird:0.70.1
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: NB_LOG_LEVEL
              value: info
            # - name: NB_HOSTNAME
            #   valueFrom:
            #     configMapKeyRef:
            #       name: netbirdproxy-params
            #       key: client-hostname
            - name: NB_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: netbirdproxy-params
                  key: management-url
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: netbirdproxy-secrets
                  key: setup-key
          livenessProbe:
            exec:
              # checks that the daemon process is responsive
              command: ["netbird", "status", "--check", "live"]
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              # checks that the client is not in an authentication-required state
              command: ["netbird", "status", "--check", "ready"]
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            exec:
              # checks that management, signal and optionally relay are connected
              command: ["netbird", "status", "--check", "startup"]
            periodSeconds: 2
            timeoutSeconds: 10
            failureThreshold: 30
          volumeMounts:
            - name: netbird-storage
              mountPath: /var/lib/netbird
      volumes:
        - name: proxy-config
          configMap:
            name: netbirdproxy
        - name: netbird-storage
          persistentVolumeClaim:
            claimName: netbirdproxy
